from typing import TypedDict, Annotated
from core.models import GatekeeperDecision
import operator

# This is the "Shared Clipboard" for our LangGraph assembly line
class AgentState(TypedDict):
    # 1. The original task pasted by the human
    raw_tt: str 
    
    # 2. The structured output generated by the Gatekeeper
    gatekeeper_decision: GatekeeperDecision 
    
    # 3. A running log of messages/feedback (the 'operator.add' means we append to the list, not overwrite it)
    messages: Annotated[list, operator.add]